export const MainLogo = require('../images/MainLogo.png')
export const homepg1 = require('../images/homepg1.jpg')
export const nearbymechanic = require('../images/nearbymechanic.jpg')
export const gasstation = require('../images/nearbygasstation.jpg')
export const towingcar = require('../images/towingcar.jpg')
export const FlatTyre = require('../images/FlatTyre.jpg')
export const Feature1 = require('../images/Feature1.jpg')
export const feature3 = require('../images/LostKey.png')
export const feature4 = require('../images/flatTyre.png')
export const feature5 = require('../images/OnsiteMinorRepair.png')
export const Benefits = require('../images/benefits.jpg')
export const OurValues = require('../images/OurValues.PNG')
export const periodicServices = require('../images/periodicservices.PNG')
export const ACservicerepair =  require('../images/ACservicerepair.PNG')
export const batteries =  require('../images/batteries.PNG')
export const Windshieldsandrepair =  require('../images/Windshields&repair.PNG')
export const tyresandwheelcare =  require('../images/tyres&Wheelcare.PNG')
export const SuspensionandFitments =  require('../images/Suspension&Fitments.PNG')
export const CarInspections =  require('../images/CarInspections.PNG')
export const CarSpaandCleaning =  require('../images/CarSpa&Cleaning.PNG')
export const ClutchandBodyParts =  require('../images/Clutch&BodyParts.PNG')
export const DentingandPainting =  require('../images/Denting&Painting.PNG')
export const detailingServices =  require('../images/detailingServices.PNG')
export const Insuranceclaims =  require('../images/Insuranceclaims.PNG') 
export const Notifications =  require('../images/notification.png')
export const userlogo =  require('../images/userlogo.png')
export const mechaniclogo =  require('../images/mechaniclogo.png')
export const serviceslogo =  require('../images/serviceslogo.png')
export const faq =  require('../images/faq.png')
export const myIcon =  require('../images/my-icon.png')
export const userreg =  require('../images/userreg.jpg')
export const mechanicLogin =  require('../images/MechanicLogin.png')
export const tyre =  require('../images/tyre.png')
export const mechanic1 =  require('../images/mechanic-1.jpg')

export const mechanic2 =  require('../images/mechanic-2.jpg')

export const mechanic3 =  require('../images/mechanic-3.jpg')
export const mechanic4 =  require('../images/mechanic4.jpg')
export const mechanic5 =  require('../images/mechanic5.jpg')
export const mechanic6 =  require('../images/mechanic6.jpg')
export const mechanic7 =  require('../images/mechanic7.jpg')

export const gas_station_icon =  require('../images/gas-station-marker.png')
export const towing_car_icon =  require('../images/towing-car_marker.png')
export const contactus =  require('../images/contactus.png')

export const kiacar =  require('../images/kiacar.png')
export const email =  require('../images/email.png')
export const location =  require('../images/location.png')
export const contact =  require('../images/contact.png')
export const customer01 =  require('../images/customer01.jpg')
export const customer02 =  require('../images/customer02.jpg')

export const TyreRepair =  require('../images/TyreRepair.webp')
export const OilChange =  require('../images/OilChange.webp')
export const CarRepair =  require('../images/CarRepair.webp')
export const Keylockout =  require('../images/Keylockout.webp')
export const BatteryJumpstar =  require('../images/BatteryJumpstar.webp')
export const CarTowing =  require('../images/CarTowing.webp')


export const mechanicworking5 =  require('../images/mechanicworking5.jpg')
export const mechanicworking4 =  require('../images/mechanicworking4.jpg')
export const mechanicworking3 =  require('../images/mechanicworking3.png')
export const mechanicworking2 =  require('../images/mechanicworking2.png')
export const mechanicworking1 =  require('../images/mechanicworking1.png')
export const AboutPageVideo =  require('../images/aboutpagevideo.mp4')

// Car Logos

export const Audi =  require('../images/audilogo.png')
export const BMW =  require('../images/bmwlogo.png')
export const Mercedes =  require('../images/mercedeslogo.png')
export const Kia =  require('../images/kialogo.png')
export const LandRover =  require('../images/landroverlogo.png')
export const Suzuki =  require('../images/suzukilogo.png')
export const Fiat =  require('../images/fiatlogo.png')
export const Toyota =  require('../images/toyotalogo.png')
export const Jeep =  require('../images/jeeplogo.png')
export const Volvo =  require('../images/volvologo.png')
export const Honda =  require('../images/hondalogo.png')
export const Ford =  require('../images/fordlogo.png')
export const Skoda =  require('../images/skodalogo.png')
export const Nissan =  require('../images/nissanlogo.png')
export const Hyundai =  require('../images/Hundailogo.png')
export const Wolkswagen =  require('../images/Wolkswagenlogo.png')
export const TATA =  require('../images/Tatalogo.png')
export const Mahindra =  require('../images/Mahindralogo.png')
export const Renault =  require('../images/RenaultLogo.png')
export const Chevrolet =  require('../images/chevroletlogo.png')
export const MechanicIntro =  require('../images/MechanicIntro.jpg')
export const UserIntro =  require('../images/UserIntro.jpg')
export const cartimg =  require('../images/cart.png')
export const gasStationMarker =  require('../images/gasStationMarker.png')


